"""Loader for inputs/tuning.xlsx — the single editable surface for every
numeric/structural knob the pipeline uses.

Why this module exists: numbers, thresholds, weights, regex patterns, and the
priority-bucket structure are all "data" — they don't belong inline in
config.py. Putting them in an Excel file with named sheets means a
non-developer at the firm can tweak them (find the row, change the value,
save) without touching Python or YAML.

config.py imports from here and re-exposes the same module-level constants
the rest of the codebase already reads (BOOSTERS, PRIORITY_BUCKETS,
SOURCE_TIER_1, MAX_PERPLEXITY_CALLS_PER_DAY, etc.). Nothing downstream
notices the move.

The Excel file is generated by `scripts/build_default_tuning_xlsx.py` from
in-code defaults; once it exists on disk, the xlsx is the source of truth.

Schema (sheets):
  Settings        — name | value | description
  Boosters        — name | weight | pattern_regex | description
  Priority Buckets — key | display | sub_buckets (semicolon-sep) | geos (semicolon-sep)
  Source Tiers    — host  (one per row, in priority order)
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parent.parent
TUNING_XLSX = ROOT / "inputs" / "tuning.xlsx"

# Sentinel for "no default supplied" so that an explicit default of None is
# distinguishable from the absence of a default.
_MISSING: Any = object()


# --- Types ----------------------------------------------------------------

@dataclass(frozen=True)
class PriorityBucket:
    """A daily-tracked category. Maps to one or more sub-buckets in keywords.xlsx.

    `geos` controls which (geo, bucket) plans the query_planner emits:
      - ("India", "US") → two plans, one India-filtered, one US-filtered
      - ("US",)         → one US plan
      - ("Global",)     → one plan querying across all geos (no Geo filter)
    """
    key: str                          # slug used in storage + ranker output
    display: str                      # human-readable label for Slack
    sub_buckets: tuple[str, ...]      # exact names from Master Keywords sheet
    geos: tuple[str, ...]


@dataclass(frozen=True)
class Tunables:
    settings: dict[str, Any]
    boosters: dict[str, tuple[float, "re.Pattern[str] | None"]]
    priority_buckets: tuple[PriorityBucket, ...]
    source_tiers: tuple[str, ...]

    def get(self, name: str, default: Any = _MISSING) -> Any:
        """Look up a Settings-sheet value. If `default` is supplied it's returned
        when the row is absent (lets new knobs ship before the xlsx is updated);
        otherwise a missing row raises with a clear pointer at the xlsx."""
        if name not in self.settings:
            if default is not _MISSING:
                return default
            raise RuntimeError(
                f"Tuning setting '{name}' not found in inputs/tuning.xlsx "
                f"'Settings' sheet. Add a row with name='{name}'."
            )
        return self.settings[name]

    def get_int(self, name: str, default: Any = _MISSING) -> int:
        v = self.get(name, default)
        try:
            return int(v)
        except (TypeError, ValueError) as e:
            raise RuntimeError(
                f"Tuning setting '{name}' must be an integer; got {v!r}."
            ) from e

    def get_float(self, name: str, default: Any = _MISSING) -> float:
        v = self.get(name, default)
        try:
            return float(v)
        except (TypeError, ValueError) as e:
            raise RuntimeError(
                f"Tuning setting '{name}' must be a number; got {v!r}."
            ) from e

    def get_str(self, name: str) -> str:
        v = self.get(name)
        if v is None:
            raise RuntimeError(f"Tuning setting '{name}' must be a non-empty string.")
        return str(v).strip()


# --- Loaders -------------------------------------------------------------

def _header_map(ws) -> dict[str, int]:
    """First row of the sheet → {column_name: column_index (0-based)}."""
    header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True))
    return {
        (str(h).strip() if h is not None else ""): i
        for i, h in enumerate(header_row)
    }


def _cell_str(v: Any) -> str | None:
    if v is None:
        return None
    s = str(v).strip()
    return s or None


def _split_semicolons(raw: Any) -> tuple[str, ...]:
    if raw is None:
        return ()
    return tuple(s.strip() for s in str(raw).split(";") if s.strip())


def _load_settings(ws) -> dict[str, Any]:
    hdr = _header_map(ws)
    for required in ("name", "value"):
        if required not in hdr:
            raise RuntimeError(
                f"tuning.xlsx 'Settings' sheet missing required column "
                f"'{required}'. Found columns: {sorted(hdr)}"
            )
    name_col, val_col = hdr["name"], hdr["value"]
    out: dict[str, Any] = {}
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        if not row or not row[name_col]:
            continue
        name = str(row[name_col]).strip()
        val = row[val_col]
        if isinstance(val, str):
            val = val.strip()
        if name in out:
            raise RuntimeError(
                f"tuning.xlsx 'Settings' sheet: duplicate name '{name}' "
                f"at row {row_idx}."
            )
        out[name] = val
    return out


def _load_boosters(ws) -> dict[str, tuple[float, "re.Pattern[str] | None"]]:
    hdr = _header_map(ws)
    for required in ("name", "weight"):
        if required not in hdr:
            raise RuntimeError(
                f"tuning.xlsx 'Boosters' sheet missing required column "
                f"'{required}'."
            )
    name_col = hdr["name"]
    weight_col = hdr["weight"]
    pattern_col = hdr.get("pattern_regex")
    out: dict[str, tuple[float, "re.Pattern[str] | None"]] = {}
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        if not row or not row[name_col]:
            continue
        name = str(row[name_col]).strip()
        try:
            weight = float(row[weight_col])
        except (TypeError, ValueError) as e:
            raise RuntimeError(
                f"tuning.xlsx 'Boosters' row {row_idx} ({name}): weight must "
                f"be a number; got {row[weight_col]!r}."
            ) from e
        pattern_str = _cell_str(row[pattern_col]) if pattern_col is not None else None
        if pattern_str:
            try:
                pattern: "re.Pattern[str] | None" = re.compile(
                    pattern_str, re.IGNORECASE,
                )
            except re.error as e:
                raise RuntimeError(
                    f"tuning.xlsx 'Boosters' row {row_idx} ({name}): invalid "
                    f"regex pattern {pattern_str!r}: {e}"
                ) from e
        else:
            pattern = None
        out[name] = (weight, pattern)
    return out


def _load_priority_buckets(ws) -> tuple[PriorityBucket, ...]:
    hdr = _header_map(ws)
    for required in ("key", "display", "sub_buckets", "geos"):
        if required not in hdr:
            raise RuntimeError(
                f"tuning.xlsx 'Priority Buckets' sheet missing required "
                f"column '{required}'."
            )
    k_col = hdr["key"]
    d_col = hdr["display"]
    s_col = hdr["sub_buckets"]
    g_col = hdr["geos"]
    out: list[PriorityBucket] = []
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        if not row or not row[k_col]:
            continue
        key = str(row[k_col]).strip()
        display = _cell_str(row[d_col]) or key
        subs = _split_semicolons(row[s_col])
        geos = _split_semicolons(row[g_col])
        if not subs:
            raise RuntimeError(
                f"tuning.xlsx 'Priority Buckets' row {row_idx} ({key}): "
                f"sub_buckets is empty. Use semicolons to separate multiple "
                f"sub-buckets."
            )
        if not geos:
            raise RuntimeError(
                f"tuning.xlsx 'Priority Buckets' row {row_idx} ({key}): "
                f"geos is empty. Allowed: India, US, Global (semicolon-separated)."
            )
        for g in geos:
            if g not in ("India", "US", "Global"):
                raise RuntimeError(
                    f"tuning.xlsx 'Priority Buckets' row {row_idx} ({key}): "
                    f"unknown geo {g!r}. Allowed: India, US, Global."
                )
        out.append(PriorityBucket(
            key=key, display=display, sub_buckets=subs, geos=geos,
        ))
    return tuple(out)


def _load_source_tiers(ws) -> tuple[str, ...]:
    out: list[str] = []
    seen: set[str] = set()
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        v = _cell_str(row[0]) if row else None
        if not v:
            continue
        if v in seen:
            raise RuntimeError(
                f"tuning.xlsx 'Source Tiers' row {row_idx}: duplicate host "
                f"{v!r}. Order matters; remove the lower-priority duplicate."
            )
        seen.add(v)
        out.append(v)
    return tuple(out)


@lru_cache(maxsize=1)
def load_tunables(path: Path = TUNING_XLSX) -> Tunables:
    """Read and parse the tuning workbook. Cached per process.

    Tests that need a fresh load (e.g. after patching the xlsx path) should
    call `load_tunables.cache_clear()`.
    """
    if not path.exists():
        raise RuntimeError(
            f"tuning.xlsx not found at {path}. Run "
            f"`python scripts/build_default_tuning_xlsx.py` to bootstrap "
            f"with defaults."
        )
    wb = load_workbook(path, read_only=True, data_only=True)
    for required_sheet in ("Settings", "Boosters", "Priority Buckets", "Source Tiers"):
        if required_sheet not in wb.sheetnames:
            raise RuntimeError(
                f"tuning.xlsx missing required sheet '{required_sheet}'. "
                f"Found sheets: {wb.sheetnames}"
            )
    return Tunables(
        settings=_load_settings(wb["Settings"]),
        boosters=_load_boosters(wb["Boosters"]),
        priority_buckets=_load_priority_buckets(wb["Priority Buckets"]),
        source_tiers=_load_source_tiers(wb["Source Tiers"]),
    )


# --- CLI -----------------------------------------------------------------

if __name__ == "__main__":
    t = load_tunables()
    print(f"Loaded tunables from {TUNING_XLSX}")
    print(f"  settings:         {len(t.settings)} entries")
    print(f"  boosters:         {len(t.boosters)} entries")
    print(f"  priority_buckets: {len(t.priority_buckets)} entries")
    print(f"  source_tiers:     {len(t.source_tiers)} entries")
    print()
    for k, v in t.settings.items():
        print(f"  {k:<35} = {v!r}")
